CREATE TABLE IF NOT EXISTS "vacier_turkey_customs_overrides" (
	"id" serial PRIMARY KEY NOT NULL,
	"sku" varchar(120) NOT NULL,
	"product_name" varchar(255),
	"customs_description" text NOT NULL,
	"customs_value" numeric(12, 2) NOT NULL,
	"tariff_code" varchar(40),
	"currency" varchar(3) DEFAULT 'EUR' NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"source" varchar(120),
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "vacier_turkey_customs_overrides_sku_idx" ON "vacier_turkey_customs_overrides" ("sku");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "vacier_turkey_customs_overrides_active_idx" ON "vacier_turkey_customs_overrides" ("is_active");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "vacier_turkey_customs_overrides_active_sku_idx" ON "vacier_turkey_customs_overrides" ("sku") WHERE is_active = true;--> statement-breakpoint
INSERT INTO "vacier_turkey_customs_overrides" ("sku", "product_name", "customs_description", "customs_value", "tariff_code", "currency", "is_active", "source")
VALUES
	('WRRISP01', 'VEER RING IN SILVER Silver', 'Sterling silver jewelry', 10.00, '711311', 'EUR', true, 'classified-products.csv'),
	('WRRIGP01', 'VEER RING WOMAN GOLD', 'VEER RING WOMAN GOLD', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('WRMNMP01', 'LINEAR RING Silver', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('WRMNGP01', 'LINEAR RING Gold', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('WRCYMP01', 'FLUID RING Silver', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('WRCYGP01', 'FLUID RING Gold', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('WNSQMP01', 'SQUARE CHAIN NECKLACE Silver', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('WNSQGP01', 'SQUARE CHAIN NECKLACE Gold', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('WNFSMP01', 'FLUID CHAIN NECKLACE Silver', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('WNFSGP01', 'FLUID CHAIN NECKLACE Gold', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('WNDSMP01', 'BRAID CHAIN NECKLACE Silver', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('WNDSGP01', 'BRAID CHAIN NECKLACE Gold', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('WNBXMP01', 'BOX CHAIN NECKLACE Silver', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('WNBXGP01', 'BOX CHAIN NECKLACE Gold', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('WNBCSS01', 'Non-Violence x Vacier Women''s Chain Necklace Silver', 'Sterling silver jewelry', 16.00, '711311', 'EUR', true, 'classified-products.csv'),
	('WNBCGS01', 'Non-Violence x Vacier Women''s Chain Necklace Gold', 'Sterling silver jewelry', 16.00, '711311', 'EUR', true, 'classified-products.csv'),
	('WEMNMP01', 'LINEAR HOOPS Silver', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('WEMNGP01', 'LINEAR HOOPS Gold', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('WECYMP01', 'FLUID HOOPS Silver', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('WECYGP01', 'FLUID HOOPS Gold', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('WCMIVP06', 'Veer Set Gold Woman', 'Veer Set Gold Woman', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('WCMIVP05', 'VEER SET IN SILVER Silver', 'Sterling silver jewelry', 23.00, '711311', 'EUR', true, 'classified-products.csv'),
	('WCMIVP04', 'FLUID SET Gold', 'Imitation jewelry', 5.00, '711719', 'EUR', true, 'classified-products.csv'),
	('WCMIVP03', 'FLUID SET Silver', 'Imitation jewelry', 5.00, '711719', 'EUR', true, 'classified-products.csv'),
	('WCMIVP02', 'LINEAR SET Gold', 'Imitation jewelry', 5.00, '711719', 'EUR', true, 'classified-products.csv'),
	('WCMIVP01', 'LINEAR SET Silver', 'Imitation jewelry', 5.00, '711719', 'EUR', true, 'classified-products.csv'),
	('WBSQMP01', 'SQUARE CHAIN BRACELET Silver', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('WBSQGP01', 'SQUARE CHAIN BRACELET Gold', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('WBRISP01', 'VEER CUFF IN SILVER Silver', 'Sterling silver jewelry', 17.00, '711311', 'EUR', true, 'classified-products.csv'),
	('WBRIGP01', 'VEER CUFF WOMAN GOLD', 'VEER CUFF WOMAN GOLD', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('WBMNMP01', 'LINEAR CUFF Silver', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('WBMNGP01', 'LINEAR CUFF Gold', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('WBFSMP01', 'FLUID CHAIN BRACELET Silver', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('WBFSGP01', 'FLUID CHAIN BRACELET Gold', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('WBDSMP01', 'BRAID CHAIN BRACELET Silver', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('WBDSGP01', 'BRAID CHAIN BRACELET Gold', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('WBCYMP01', 'FLUID CUFF Silver', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('WBCYGP01', 'FLUID CUFF Gold', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('WBBXMP01', 'BOX CHAIN BRACELET Silver', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('WBBXGP01', 'BOX CHAIN BRACELET Gold', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('WBBCSS01', 'Non-Violence x Vacier Women''s Chain Bracelet Silver', 'Sterling silver jewelry', 11.00, '711311', 'EUR', true, 'classified-products.csv'),
	('WBBCGS01', 'Non-Violence x Vacier Women''s Chain Bracelet Gold', 'Sterling silver jewelry', 11.00, '711311', 'EUR', true, 'classified-products.csv'),
	('VRSISP02', 'RIPPLE SIGNET RING IN SILVER Silver', 'Sterling silver jewelry', 13.00, '711311', 'EUR', true, 'classified-products.csv'),
	('VRSISP01', 'UNISIZE SIGNET RING IN SILVER Silver', 'Imitation jewelry', 6.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VRSIGP01', 'RIPPLE SIGNET RING IN GOLD', 'RIPPLE SIGNET RING IN GOLD', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('VRRISP01', 'VEER RING IN SILVER Silver', 'Sterling silver jewelry', 10.00, '711311', 'EUR', true, 'classified-products.csv'),
	('VRRIGP01', 'VEER RING MAN GOLD', 'VEER RING MAN GOLD', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('VROPSSP01', 'STACKABLE UNISIZE RING Silver', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VROPSP01', 'EXCLUSIVE UNISIZE RING IN SILVER Silver', 'Imitation jewelry', 6.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VROPSGP02', 'STACKABLE UNISIZE RING Gold', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VROPMP02', 'MINIMAL UNISIZE RING Silver', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VROPMB02', 'UNISIZE RING Silver', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VROPGP02', 'MINIMAL UNISIZE RING Gold', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VROPGB02', 'UNISIZE RING Gold', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VROPBMB03', 'STACKABLE UNISIZE RING Black', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VROPBMB02', 'UNISIZE RING Black', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VROPBMB01', 'MINIMAL UNISIZE RING Black', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VPPOPN02', 'VERSATILE VACIER WALLET', 'Wallet with outer surface of plastic sheeting', 10.00, '42023210', 'EUR', true, 'classified-products.csv'),
	('VPENPN05', '‍RIPPLE CARD HOLDER TAN (100% off)', 'Wallet with outer surface of plastic sheeting', 10.00, '42023210', 'EUR', true, 'classified-products.csv'),
	('VPENPN04', '‍RIPPLE CARD HOLDER SAND (100% off)', 'Wallet with outer surface of plastic sheeting', 10.00, '42023210', 'EUR', true, 'classified-products.csv'),
	('VPENPN03', 'RIPPLE CARD HOLDER BLACK', 'Wallet with outer surface of plastic sheeting', 10.00, '42023210', 'EUR', true, 'classified-products.csv'),
	('VPENPN02', 'RIPPLE CARD HOLDER DARK BLUE', 'Wallet with outer surface of plastic sheeting', 10.00, '42023210', 'EUR', true, 'classified-products.csv'),
	('VPENMN01', 'MINIMAL VACIER WALLET', 'Wallet with outer surface of plastic sheeting', 10.00, '42023210', 'EUR', true, 'classified-products.csv'),
	('VPBALN03', 'Bubble Mailer', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VNWCMN02', 'WIRE CHAIN NECKLACE Silver', 'Imitation jewelry', 5.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VNWCMN01', 'WIRE PENDANT NECKLACE Silver', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VNWCMN0', 'WIRE PENDANT NECKLACE Silver', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VNWCGN02', 'WIRE CHAIN NECKLACE Gold', 'Imitation jewelry', 5.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VNWCGN01', 'WIRE PENDANT NECKLACE Gold', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VNWCBMB02', 'WIRE PENDANT NECKLACE Black', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VNWCBMB01', 'WIRE CHAIN NECKLACE Black', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VNSQMN02', 'SQUARE CHAIN NECKLACE Silver', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VNSQMN01', 'SQUARE PENDANT NECKLACE Silver', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VNSQGN02', 'SQUARE CHAIN NECKLACE Gold', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VNSQGN01', 'SQUARE PENDANT NECKLACE Gold', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VNSQBMB02', 'SQUARE PENDANT NECKLACE Black', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VNSQBMB01', 'SQUARE CHAIN NECKLACE Black', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VNSEMP01', 'LINEAR CHAIN NECKLACE Silver', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VNSEGP01', 'LINEAR CHAIN NECKLACE Gold', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VNSEBMB01', 'LINEAR CHAIN NECKLACE Black', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VNOCSN01', 'OCTAGON CHAIN NECKLACE IN SILVER Silver', 'Sterling silver jewelry', 11.00, '711311', 'EUR', true, 'classified-products.csv'),
	('VNCLSN01', 'CLIP CHAIN NECKLACE IN SILVER Silver', 'Sterling silver jewelry', 11.00, '711311', 'EUR', true, 'classified-products.csv'),
	('VNCCMN02', 'MINIMAL CHAIN NECKLACE Silver', 'Imitation jewelry', 5.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VNCCMN01', 'MINIMAL PENDANT NECKLACE Silver', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VNCCGN02', 'MINIMAL CHAIN NECKLACE Gold', 'Imitation jewelry', 5.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VNCCGN01', 'MINIMAL PENDANT NECKLACE Gold', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VNCCBMB02', 'MINIMAL PENDANT NECKLACE Black', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VNCCBMB01', 'MINIMAL CHAIN NECKLACE Black', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VNBOMN02', 'BOX CHAIN NECKLACE Silver', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VNBOMN01', 'BOX PENDANT NECKLACE Silver', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VNBOGN02', 'BOX CHAIN NECKLACE Gold', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VNBOGN01', 'BOX PENDANT NECKLACE Gold', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VNBOBMB02', 'BOX PENDANT NECKLACE Black', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VNBOBMB01', 'BOX CHAIN NECKLACE Black', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VNBCSS01', 'Non-Violence x Vacier Men''s Chain Necklace Silver', 'Sterling silver jewelry', 0.00, '7113110', 'EUR', true, 'classified-products.csv'),
	('VNBCGS01', 'Non-Violence x Vacier Men''s Chain Necklace Gold', 'Sterling silver jewelry', 16.00, '711311', 'EUR', true, 'classified-products.csv'),
	('versatile-vacier-wallet-100-off', 'VERSATILE VACIER WALLET (100% off)', 'Wallet with outer surface of plastic sheeting', 2.00, '42023210', 'EUR', true, 'classified-products.csv'),
	('VCMIVP10', 'STACKABLE UNISIZE SET Silver', 'Imitation jewelry', 5.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VCMIVP09', 'STACKABLE UNISIZE SET Gold', 'Imitation jewelry', 5.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VCMIVP08', 'Veer Set Man Gold', 'Veer Set Man Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('VCMIVP07', 'VEER SET IN SILVER Silver', 'Sterling silver jewelry', 23.00, '711311', 'EUR', true, 'classified-products.csv'),
	('VCMIVP06', 'RIPPLE SIGNET SET IN GOLD', 'RIPPLE SIGNET SET IN GOLD', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('VCMIVP05', 'RIPPLE SIGNET SET IN SILVER Silver', 'Sterling silver jewelry', 33.00, '711311', 'EUR', true, 'classified-products.csv'),
	('VCMIVP04', 'MINIMAL UNISIZE SET Gold', 'Imitation jewelry', 5.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VCMIVP03', 'MINIMAL UNISIZE SET Silver', 'Imitation jewelry', 5.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VCMIVP02', 'UNISIZE SIGNET SET IN SILVER Silver', 'Sterling silver jewelry', 34.00, '711311', 'EUR', true, 'classified-products.csv'),
	('VCMIVP01', 'EXCLUSIVE UNISIZE SILVER SET Silver', 'Sterling silver jewelry', 25.00, '711311', 'EUR', true, 'classified-products.csv'),
	('VCMIVN01', 'Vacier Gift Box and Cloth', 'Paperboard packaging box', 0.00, '48195000', 'EUR', true, 'classified-products.csv'),
	('VCMIVB04', 'UNISIZE SET Gold', 'Imitation jewelry', 5.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VCMIVB03', 'UNISIZE SET Silver', 'Imitation jewelry', 5.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VCMIVB01', 'STACKABLE UNISIZE SET Black', 'Imitation jewelry', 5.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VCMIBMB08', 'MINIMAL UNISIZE SET Black', 'Imitation jewelry', 5.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VCMIBMB07', 'UNISIZE SET Black', 'Imitation jewelry', 5.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBWCMN03', 'WIRE CHAIN BRACELET Extra Small (Fits XXS-XS) / Silver', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBWCMN02', 'WIRE CHAIN BRACELET Extra Large (Fits XL- XXL) / Silver', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBWCMN01', 'WIRE CHAIN BRACELET Regular - Fits Most (Small to Large) / Silver', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBWCGN03', 'WIRE CHAIN BRACELET Extra Small (Fits XXS-XS) / Gold', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBWCGN02', 'WIRE CHAIN BRACELET Extra Large (Fits XL- XXL) / Gold', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBWCGN01', 'WIRE CHAIN BRACELET Regular - Fits Most (Small to Large) / Gold', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBWCBMB03', 'WIRE CHAIN BRACELET Extra Small (Fits XXS-XS) / Black', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBWCBMB02', 'WIRE CHAIN BRACELET Extra Large (Fits XL- XXL) / Black', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBWCBMB01', 'WIRE CHAIN BRACELET Regular - Fits Most (Small to Large) / Black', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBSQMN03', 'SQUARE CHAIN BRACELET Extra Small (Fits XXS-XS) / Silver', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBSQMN02', 'SQUARE CHAIN BRACELET Extra Large (Fits XL- XXL) / Silver', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBSQMN01', 'SQUARE CHAIN BRACELET Regular - Fits Most (Small to Large) / Silver', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBSQGN03', 'SQUARE CHAIN BRACELET Extra Small (Fits XXS-XS) / Gold', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBSQGN02', 'SQUARE CHAIN BRACELET Extra Large (Fits XL- XXL) / Gold', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBSQGN01', 'SQUARE CHAIN BRACELET Regular - Fits Most (Small to Large) / Gold', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBSQBMB03', 'SQUARE CHAIN BRACELET (Copy) Black / Extra Small (Fits XXS-XS)', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBSQBMB02', 'SQUARE CHAIN BRACELET (Copy) Black / Extra Large (Fits XL- XXL)', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBSQBMB01', 'SQUARE CHAIN BRACELET (Copy) Black / Regular - Fits Most (Small to Large)', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBSISP02', 'RIPPLE SIGNET CUFF IN SILVER Silver', 'Sterling silver jewelry', 23.00, '711311', 'EUR', true, 'classified-products.csv'),
	('VBSISP01', 'UNISIZE SIGNET CUFF IN SILVER Silver', 'Sterling silver jewelry', 20.00, '711311', 'EUR', true, 'classified-products.csv'),
	('VBSIGP01', 'RIPPLE SIGNET CUFF IN GOLD', 'RIPPLE SIGNET CUFF IN GOLD', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('VBSEMP03', 'LINEAR CHAIN BRACELET Extra Small (Fits XXS-XS) / Silver', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBSEMP02', 'LINEAR CHAIN BRACELET Extra Large (Fits XL- XXL) / Silver', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBSEMP01', 'LINEAR CHAIN BRACELET Regular - Fits Most (Small to Large) / Silver', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBSEGP03', 'LINEAR CHAIN BRACELET Extra Small (Fits XXS-XS) / Gold', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBSEGP02', 'LINEAR CHAIN BRACELET Extra Large (Fits XL- XXL) / Gold', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBSEGP01', 'LINEAR CHAIN BRACELET Regular - Fits Most (Small to Large) / Gold', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBSEBMB03', 'LINEAR CHAIN BRACELET Extra Small (Fits XXS-XS) / Black', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBSEBMB02', 'LINEAR CHAIN BRACELET Extra Large (Fits XL- XXL) / Black', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBSEBMB01', 'LINEAR CHAIN BRACELET Regular - Fits Most (Small to Large) / Black', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBRISP01', 'VEER CUFF IN SILVER Silver', 'Sterling silver jewelry', 17.00, '711311', 'EUR', true, 'classified-products.csv'),
	('VBRIGP01', 'VEER CUFF MAN GOLD', 'VEER CUFF MAN GOLD', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('VBOCSN03', 'OCTAGON BRACELET IN SILVER Extra Small (Fits XXS-XS) / Silver', 'Sterling silver jewelry', 10.00, '711311', 'EUR', true, 'classified-products.csv'),
	('VBOCSN02', 'OCTAGON BRACELET IN SILVER Extra Large (Fits XL- XXL) / Silver', 'Sterling silver jewelry', 10.00, '711311', 'EUR', true, 'classified-products.csv'),
	('VBOCSN01', 'OCTAGON BRACELET IN SILVER Regular - Fits Most (Small to Large) / Silver', 'Sterling silver jewelry', 10.00, '711311', 'EUR', true, 'classified-products.csv'),
	('VBCUSSP01', 'STACKABLE UNISIZE CUFF Silver', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBCUSP01', 'EXCLUSIVE UNISIZE CUFF IN SILVER Silver', 'Sterling silver jewelry', 16.00, '711311', 'EUR', true, 'classified-products.csv'),
	('VBCUSGP02', 'STACKABLE UNISIZE CUFF Gold', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBCUMP02', 'MINIMAL UNISIZE CUFF Silver', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBCUMB02', 'UNISIZE CUFF Silver', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBCUGP02', 'MINIMAL UNISIZE CUFF Gold', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBCUGB02', 'UNISIZE CUFF Gold', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBCUBMB03', 'STACKABLE UNISIZE CUFF Black', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBCUBMB02', 'UNISIZE CUFF Black', 'Imitation jewelry', 4.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBCUBMB01', 'MINIMAL UNISIZE CUFF Black', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBCLSN03', 'CLIP CHAIN BRACELET IN SILVER Silver / Extra Small (Fits XXS-XS)', 'Sterling silver jewelry', 10.00, '711311', 'EUR', true, 'classified-products.csv'),
	('VBCLSN02', 'CLIP CHAIN BRACELET IN SILVER Silver / Extra Large (Fits XL-XXL)', 'Sterling silver jewelry', 10.00, '711311', 'EUR', true, 'classified-products.csv'),
	('VBCLSN01', 'CLIP CHAIN BRACELET IN SILVER Silver / Regular - Fits Most (Small to Large)', 'Sterling silver jewelry', 10.00, '711311', 'EUR', true, 'classified-products.csv'),
	('VBCCMN03', 'MINIMAL CHAIN BRACELET Extra Small (Fits XXS-XS) / Silver', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBCCMN02', 'MINIMAL CHAIN BRACELET Extra Large (Fits XL- XXL) / Silver', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBCCMN01', 'MINIMAL CHAIN BRACELET Regular - Fits Most (Small to Large) / Silver', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBCCGN03', 'MINIMAL CHAIN BRACELET Extra Small (Fits XXS-XS) / Gold', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBCCGN02', 'MINIMAL CHAIN BRACELET Extra Large (Fits XL- XXL) / Gold', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBCCGN01', 'MINIMAL CHAIN BRACELET Regular - Fits Most (Small to Large) / Gold', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBCCBMB03', 'MINIMAL CHAIN BRACELET Extra Small (Fits XXS-XS) / Black', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBCCBMB02', 'MINIMAL CHAIN BRACELET Extra Large (Fits XL- XXL) / Black', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBCCBMB01', 'MINIMAL CHAIN BRACELET Regular - Fits Most (Small to Large) / Black', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBBOMN03', 'BOX CHAIN BRACELET Extra Small (Fits XXS-XS) / Silver', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBBOMN02', 'BOX CHAIN BRACELET Extra Large (Fits XL- XXL) / Silver', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBBOMN01', 'BOX CHAIN BRACELET Regular - Fits Most (Small to Large) / Silver', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBBOGN03', 'BOX CHAIN BRACELET Extra Small (Fits XXS-XS) / Gold', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBBOGN02', 'BOX CHAIN BRACELET Extra Large (Fits XL- XXL) / Gold', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBBOGN01', 'BOX CHAIN BRACELET Regular - Fits Most (Small to Large) / Gold', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBBOBMB03', 'BOX CHAIN BRACELET Extra Small (Fits XXS-XS) / Black', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBBOBMB02', 'BOX CHAIN BRACELET Extra Large (Fits XL- XXL) / Black', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBBOBMB01', 'BOX CHAIN BRACELET Regular - Fits Most (Small to Large) / Black', 'Imitation jewelry', 3.00, '711719', 'EUR', true, 'classified-products.csv'),
	('VBBCSS01', 'Non-Violence x Vacier Men''s Chain Bracelet Silver', 'Sterling silver jewelry', 0.00, '71131100', 'EUR', true, 'classified-products.csv'),
	('VBBCGS01', 'Non-Violence x Vacier Men''s Chain Bracelet Gold', 'Sterling silver jewelry', 11.00, '711311', 'EUR', true, 'classified-products.csv'),
	('VACOTN01', 'Silver Cloth', 'Microfiber cleaning cloth', 0.00, '63071090', 'EUR', true, 'classified-products.csv'),
	('VACARN01', 'Thank you for the support!', 'Thank you for the support!', 0.00, '48171000', 'EUR', true, 'classified-products.csv'),
	('VABXRN01', 'Gift Box', 'Paperboard packaging box', 0.00, '48195000', 'EUR', true, 'classified-products.csv'),
	('BUBBLEMAILER', 'Vacier Bubble Mailer', 'Plastic Envelope with bubble protection inside.', 0.00, '48171000', 'EUR', true, 'classified-products.csv'),
	('628c9d3fa115a', 'Vacier Gift Card €50.00', 'Vacier Gift Card €50.00', 0.00, '711719', 'EUR', true, 'classified-products.csv'),
	('628c9d3edc0b6', 'Vacier Gift Card €25.00', 'Vacier Gift Card €25.00', 0.00, '711719', 'EUR', true, 'classified-products.csv'),
	('628c9d3e33375', 'Vacier Gift Card €100.00', 'Vacier Gift Card €100.00', 0.00, '711719', 'EUR', true, 'classified-products.csv'),
	('628c9d3da1f36', 'Vacier Gift Card €10.00', 'Vacier Gift Card €10.00', 0.00, '711719', 'EUR', true, 'classified-products.csv'),
	('57384038564222', '‍RIPPLE CARD HOLDER SAND (100% off)', '‍RIPPLE CARD HOLDER SAND (100% off)', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57384038498686', '‍RIPPLE CARD HOLDER DARK BLUE (100% off)', '‍RIPPLE CARD HOLDER DARK BLUE (100% off)', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57384038269310', '‍RIPPLE CARD HOLDER BLACK (100% off)', '‍RIPPLE CARD HOLDER BLACK (100% off)', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57382603522430', '‍VERSATILE VACIER WALLET (100% off)', '‍VERSATILE VACIER WALLET (100% off)', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57370855506302', 'Ripple Card Holder Brown', 'Ripple Card Holder Brown', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57370855473534', 'Ripple Card Holder Beige', 'Ripple Card Holder Beige', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57370855440766', 'Ripple Card Holder Blue', 'Ripple Card Holder Blue', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57370855407998', 'Ripple Card Holder Black', 'Ripple Card Holder Black', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57214809145726', 'RIPPLE CARD HOLDER SAND', 'RIPPLE CARD HOLDER SAND', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57214808326526', 'RIPPLE CARD HOLDER TAN', 'RIPPLE CARD HOLDER TAN', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57214806589822', 'RIPPLE CARD HOLDER DARK BLUE', 'RIPPLE CARD HOLDER DARK BLUE', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57214803771774', 'RIPPLE CARD HOLDER BLACK', 'RIPPLE CARD HOLDER BLACK', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57214794203518', 'RIPPLE CARD HIOLDER BLACK', 'RIPPLE CARD HIOLDER BLACK', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57214309990782', 'RIPPLE CARD HOLDER IN BLUE', 'RIPPLE CARD HOLDER IN BLUE', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57214309335422', 'RIPPLE CARD HOLDER IN BLACK', 'RIPPLE CARD HOLDER IN BLACK', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134559330686', 'Men''s Cuff+Bracelets Bundle Black / Black / Black', 'Men''s Cuff+Bracelets Bundle Black / Black / Black', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134559297918', 'Men''s Cuff+Bracelets Bundle Black / Black / Gold', 'Men''s Cuff+Bracelets Bundle Black / Black / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134559265150', 'Men''s Cuff+Bracelets Bundle Black / Black / Silver', 'Men''s Cuff+Bracelets Bundle Black / Black / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134559232382', 'Men''s Cuff+Bracelets Bundle Black / Gold / Black', 'Men''s Cuff+Bracelets Bundle Black / Gold / Black', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134559199614', 'Men''s Cuff+Bracelets Bundle Black / Gold / Gold', 'Men''s Cuff+Bracelets Bundle Black / Gold / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134559166846', 'Men''s Cuff+Bracelets Bundle Black / Gold / Silver', 'Men''s Cuff+Bracelets Bundle Black / Gold / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134559134078', 'Men''s Cuff+Bracelets Bundle Black / Silver / Black', 'Men''s Cuff+Bracelets Bundle Black / Silver / Black', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134559101310', 'Men''s Cuff+Bracelets Bundle Black / Silver / Gold', 'Men''s Cuff+Bracelets Bundle Black / Silver / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134559068542', 'Men''s Cuff+Bracelets Bundle Black / Silver / Silver', 'Men''s Cuff+Bracelets Bundle Black / Silver / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134559035774', 'Men''s Cuff+Bracelets Bundle Gold / Black / Black', 'Men''s Cuff+Bracelets Bundle Gold / Black / Black', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134559003006', 'Men''s Cuff+Bracelets Bundle Gold / Black / Gold', 'Men''s Cuff+Bracelets Bundle Gold / Black / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134558970238', 'Men''s Cuff+Bracelets Bundle Gold / Black / Silver', 'Men''s Cuff+Bracelets Bundle Gold / Black / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134558937470', 'Men''s Cuff+Bracelets Bundle Gold / Gold / Black', 'Men''s Cuff+Bracelets Bundle Gold / Gold / Black', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134558904702', 'Men''s Cuff+Bracelets Bundle Gold / Gold / Gold', 'Men''s Cuff+Bracelets Bundle Gold / Gold / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134558871934', 'Men''s Cuff+Bracelets Bundle Gold / Gold / Silver', 'Men''s Cuff+Bracelets Bundle Gold / Gold / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134558839166', 'Men''s Cuff+Bracelets Bundle Gold / Silver / Black', 'Men''s Cuff+Bracelets Bundle Gold / Silver / Black', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134558806398', 'Men''s Cuff+Bracelets Bundle Gold / Silver / Gold', 'Men''s Cuff+Bracelets Bundle Gold / Silver / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134558773630', 'Men''s Cuff+Bracelets Bundle Gold / Silver / Silver', 'Men''s Cuff+Bracelets Bundle Gold / Silver / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134558740862', 'Men''s Cuff+Bracelets Bundle Silver / Black / Black', 'Men''s Cuff+Bracelets Bundle Silver / Black / Black', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134558708094', 'Men''s Cuff+Bracelets Bundle Silver / Black / Gold', 'Men''s Cuff+Bracelets Bundle Silver / Black / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134558675326', 'Men''s Cuff+Bracelets Bundle Silver / Black / Silver', 'Men''s Cuff+Bracelets Bundle Silver / Black / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134558642558', 'Men''s Cuff+Bracelets Bundle Silver / Gold / Black', 'Men''s Cuff+Bracelets Bundle Silver / Gold / Black', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134558609790', 'Men''s Cuff+Bracelets Bundle Silver / Gold / Gold', 'Men''s Cuff+Bracelets Bundle Silver / Gold / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134558577022', 'Men''s Cuff+Bracelets Bundle Silver / Gold / Silver', 'Men''s Cuff+Bracelets Bundle Silver / Gold / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134558544254', 'Men''s Cuff+Bracelets Bundle Silver / Silver / Black', 'Men''s Cuff+Bracelets Bundle Silver / Silver / Black', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134558511486', 'Men''s Cuff+Bracelets Bundle Silver / Silver / Gold', 'Men''s Cuff+Bracelets Bundle Silver / Silver / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134558478718', 'Men''s Cuff+Bracelets Bundle Silver / Silver / Silver', 'Men''s Cuff+Bracelets Bundle Silver / Silver / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134089568638', 'Men''s 925 Silver Bundle', 'Men''s 925 Silver Bundle', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134084456830', 'Men''s Bracelet Bundle Black / Black', 'Men''s Bracelet Bundle Black / Black', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134084424062', 'Men''s Bracelet Bundle Black / Gold', 'Men''s Bracelet Bundle Black / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134084391294', 'Men''s Bracelet Bundle Black / Silver', 'Men''s Bracelet Bundle Black / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134084358526', 'Men''s Bracelet Bundle Gold / Black', 'Men''s Bracelet Bundle Gold / Black', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134084325758', 'Men''s Bracelet Bundle Gold / Gold', 'Men''s Bracelet Bundle Gold / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134084292990', 'Men''s Bracelet Bundle Gold / Silver', 'Men''s Bracelet Bundle Gold / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134084260222', 'Men''s Bracelet Bundle Silver / Black', 'Men''s Bracelet Bundle Silver / Black', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134084227454', 'Men''s Bracelet Bundle Silver / Gold', 'Men''s Bracelet Bundle Silver / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134084194686', 'Men''s Bracelet Bundle Silver / Silver', 'Men''s Bracelet Bundle Silver / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134054736254', 'Women''s Ring Bundle Silver / Silver', 'Women''s Ring Bundle Silver / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134054703486', 'Women''s Ring Bundle Silver / Gold', 'Women''s Ring Bundle Silver / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134054670718', 'Women''s Ring Bundle Gold / Silver', 'Women''s Ring Bundle Gold / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134054637950', 'Women''s Ring Bundle Gold / Gold', 'Women''s Ring Bundle Gold / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134028783998', 'Women''s Cuff Bundle Silver / Silver', 'Women''s Cuff Bundle Silver / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134028751230', 'Women''s Cuff Bundle Silver / Gold', 'Women''s Cuff Bundle Silver / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134028718462', 'Women''s Cuff Bundle Gold / Silver', 'Women''s Cuff Bundle Gold / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57134028685694', 'Women''s Cuff Bundle Gold / Gold', 'Women''s Cuff Bundle Gold / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57129473507710', 'Women''s Necklace Bundle Silver / Silver', 'Women''s Necklace Bundle Silver / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57129473474942', 'Women''s Necklace Bundle Silver / Gold', 'Women''s Necklace Bundle Silver / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57129473442174', 'Women''s Necklace Bundle Gold / Silver', 'Women''s Necklace Bundle Gold / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57129473409406', 'Women''s Necklace Bundle Gold / Gold', 'Women''s Necklace Bundle Gold / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57129460924798', 'Men''s Minimal Bundle Black / Black', 'Men''s Minimal Bundle Black / Black', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57129460892030', 'Men''s Minimal Bundle Black / Gold', 'Men''s Minimal Bundle Black / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57129460859262', 'Men''s Minimal Bundle Black / Silver', 'Men''s Minimal Bundle Black / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57129460826494', 'Men''s Minimal Bundle Gold / Black', 'Men''s Minimal Bundle Gold / Black', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57129460793726', 'Men''s Minimal Bundle Gold / Gold', 'Men''s Minimal Bundle Gold / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57129460760958', 'Men''s Minimal Bundle Gold / Silver', 'Men''s Minimal Bundle Gold / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57129460728190', 'Men''s Minimal Bundle Silver / Black', 'Men''s Minimal Bundle Silver / Black', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57129460695422', 'Men''s Minimal Bundle Silver / Gold', 'Men''s Minimal Bundle Silver / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57129460662654', 'Men''s Minimal Bundle Silver / Silver', 'Men''s Minimal Bundle Silver / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57129408495998', 'Women''s Cuff+Bracelet Bundle Silver / Silver', 'Women''s Cuff+Bracelet Bundle Silver / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57129408463230', 'Women''s Cuff+Bracelet Bundle Silver / Gold', 'Women''s Cuff+Bracelet Bundle Silver / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57129408430462', 'Women''s Cuff+Bracelet Bundle Gold / Silver', 'Women''s Cuff+Bracelet Bundle Gold / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57129408397694', 'Women''s Cuff+Bracelet Bundle Gold / Gold', 'Women''s Cuff+Bracelet Bundle Gold / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57004517720446', 'Men''s Ring+Cuff+Bracelet Bundle Black / Black / Black', 'Men''s Ring+Cuff+Bracelet Bundle Black / Black / Black', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57004517687678', 'Men''s Ring+Cuff+Bracelet Bundle Black / Black / Gold', 'Men''s Ring+Cuff+Bracelet Bundle Black / Black / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57004517654910', 'Men''s Ring+Cuff+Bracelet Bundle Black / Black / Silver', 'Men''s Ring+Cuff+Bracelet Bundle Black / Black / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57004517622142', 'Men''s Ring+Cuff+Bracelet Bundle Black / Gold / Black', 'Men''s Ring+Cuff+Bracelet Bundle Black / Gold / Black', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57004517589374', 'Men''s Ring+Cuff+Bracelet Bundle Black / Gold / Gold', 'Men''s Ring+Cuff+Bracelet Bundle Black / Gold / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57004517556606', 'Men''s Ring+Cuff+Bracelet Bundle Black / Gold / Silver', 'Men''s Ring+Cuff+Bracelet Bundle Black / Gold / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57004517523838', 'Men''s Ring+Cuff+Bracelet Bundle Black / Silver / Black', 'Men''s Ring+Cuff+Bracelet Bundle Black / Silver / Black', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57004517491070', 'Men''s Ring+Cuff+Bracelet Bundle Black / Silver / Gold', 'Men''s Ring+Cuff+Bracelet Bundle Black / Silver / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57004517458302', 'Men''s Ring+Cuff+Bracelet Bundle Black / Silver / Silver', 'Men''s Ring+Cuff+Bracelet Bundle Black / Silver / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57004517425534', 'Men''s Ring+Cuff+Bracelet Bundle Gold / Black / Black', 'Men''s Ring+Cuff+Bracelet Bundle Gold / Black / Black', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57004517392766', 'Men''s Ring+Cuff+Bracelet Bundle Gold / Black / Gold', 'Men''s Ring+Cuff+Bracelet Bundle Gold / Black / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57004517359998', 'Men''s Ring+Cuff+Bracelet Bundle Gold / Black / Silver', 'Men''s Ring+Cuff+Bracelet Bundle Gold / Black / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57004517327230', 'Men''s Ring+Cuff+Bracelet Bundle Gold / Gold / Black', 'Men''s Ring+Cuff+Bracelet Bundle Gold / Gold / Black', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57004517294462', 'Men''s Ring+Cuff+Bracelet Bundle Gold / Gold / Gold', 'Men''s Ring+Cuff+Bracelet Bundle Gold / Gold / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57004517261694', 'Men''s Ring+Cuff+Bracelet Bundle Gold / Gold / Silver', 'Men''s Ring+Cuff+Bracelet Bundle Gold / Gold / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57004517228926', 'Men''s Ring+Cuff+Bracelet Bundle Gold / Silver / Black', 'Men''s Ring+Cuff+Bracelet Bundle Gold / Silver / Black', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57004517196158', 'Men''s Ring+Cuff+Bracelet Bundle Gold / Silver / Gold', 'Men''s Ring+Cuff+Bracelet Bundle Gold / Silver / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57004517163390', 'Men''s Ring+Cuff+Bracelet Bundle Gold / Silver / Silver', 'Men''s Ring+Cuff+Bracelet Bundle Gold / Silver / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57004517130622', 'Men''s Ring+Cuff+Bracelet Bundle Silver / Black / Black', 'Men''s Ring+Cuff+Bracelet Bundle Silver / Black / Black', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57004517097854', 'Men''s Ring+Cuff+Bracelet Bundle Silver / Black / Gold', 'Men''s Ring+Cuff+Bracelet Bundle Silver / Black / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57004517065086', 'Men''s Ring+Cuff+Bracelet Bundle Silver / Black / Silver', 'Men''s Ring+Cuff+Bracelet Bundle Silver / Black / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57004517032318', 'Men''s Ring+Cuff+Bracelet Bundle Silver / Gold / Black', 'Men''s Ring+Cuff+Bracelet Bundle Silver / Gold / Black', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57004516999550', 'Men''s Ring+Cuff+Bracelet Bundle Silver / Gold / Gold', 'Men''s Ring+Cuff+Bracelet Bundle Silver / Gold / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57004516966782', 'Men''s Ring+Cuff+Bracelet Bundle Silver / Gold / Silver', 'Men''s Ring+Cuff+Bracelet Bundle Silver / Gold / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57004516934014', 'Men''s Ring+Cuff+Bracelet Bundle Silver / Silver / Black', 'Men''s Ring+Cuff+Bracelet Bundle Silver / Silver / Black', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57004516901246', 'Men''s Ring+Cuff+Bracelet Bundle Silver / Silver / Gold', 'Men''s Ring+Cuff+Bracelet Bundle Silver / Silver / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57004516868478', 'Men''s Ring+Cuff+Bracelet Bundle Silver / Silver / Silver', 'Men''s Ring+Cuff+Bracelet Bundle Silver / Silver / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57004501795198', 'Men''s Cuff+Bracelet Bundle Black / Black', 'Men''s Cuff+Bracelet Bundle Black / Black', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57004501762430', 'Men''s Cuff+Bracelet Bundle Black / Gold', 'Men''s Cuff+Bracelet Bundle Black / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57004501729662', 'Men''s Cuff+Bracelet Bundle Black / Silver', 'Men''s Cuff+Bracelet Bundle Black / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57004501696894', 'Men''s Cuff+Bracelet Bundle Gold / Black', 'Men''s Cuff+Bracelet Bundle Gold / Black', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57004501664126', 'Men''s Cuff+Bracelet Bundle Gold / Gold', 'Men''s Cuff+Bracelet Bundle Gold / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57004501631358', 'Men''s Cuff+Bracelet Bundle Gold / Silver', 'Men''s Cuff+Bracelet Bundle Gold / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57004501598590', 'Men''s Cuff+Bracelet Bundle Silver / Black', 'Men''s Cuff+Bracelet Bundle Silver / Black', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57004501565822', 'Men''s Cuff+Bracelet Bundle Silver / Gold', 'Men''s Cuff+Bracelet Bundle Silver / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('57004501533054', 'Men''s Cuff+Bracelet Bundle Silver / Silver', 'Men''s Cuff+Bracelet Bundle Silver / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56891072610686', 'Men''s Bestsellers Bundle Black / Black', 'Men''s Bestsellers Bundle Black / Black', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56891072577918', 'Men''s Bestsellers Bundle Gold / Black', 'Men''s Bestsellers Bundle Gold / Black', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56891072545150', 'Men''s Bestsellers Bundle Silver / Black', 'Men''s Bestsellers Bundle Silver / Black', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56891061633406', 'Men''s Bestsellers Bundle Black / Gold', 'Men''s Bestsellers Bundle Black / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56891061567870', 'Men''s Bestsellers Bundle Black / Silver', 'Men''s Bestsellers Bundle Black / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56822662988158', 'Women''s Bestsellers Bundle Silver / Silver / Silver', 'Women''s Bestsellers Bundle Silver / Silver / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56822662955390', 'Women''s Bestsellers Bundle Silver / Gold / Silver', 'Women''s Bestsellers Bundle Silver / Gold / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56822662922622', 'Women''s Bestsellers Bundle Gold / Silver / Silver', 'Women''s Bestsellers Bundle Gold / Silver / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56822662889854', 'Women''s Bestsellers Bundle Gold / Gold / Silver', 'Women''s Bestsellers Bundle Gold / Gold / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56747879301502', 'Vacier Gift Card €100.00', 'Vacier Gift Card €100.00', 0.00, '711719', 'EUR', true, 'classified-products.csv'),
	('56747879268734', 'Vacier Gift Card €50.00', 'Vacier Gift Card €50.00', 0.00, '711719', 'EUR', true, 'classified-products.csv'),
	('56747854856574', 'Vacier Gift Card €', 'Vacier Gift Card €', 0.00, '711719', 'EUR', true, 'classified-products.csv'),
	('56730754679166', 'Vacier Gift Card €250.00', 'Vacier Gift Card €250.00', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56730754646398', 'Vacier Gift Card €100.00', 'Vacier Gift Card €100.00', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56730754613630', 'Vacier Gift Card €50.00', 'Vacier Gift Card €50.00', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56730754580862', 'Vacier Gift Card €25.00', 'Vacier Gift Card €25.00', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528789078398', 'Female All Set Bestsellers (Offer No.4) Silver / Silver / Silver', 'Female All Set Bestsellers (Offer No.4) Silver / Silver / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528789045630', 'Female All Set Bestsellers (Offer No.4) Silver / Silver / Gold', 'Female All Set Bestsellers (Offer No.4) Silver / Silver / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528789012862', 'Female All Set Bestsellers (Offer No.4) Silver / Gold / Silver', 'Female All Set Bestsellers (Offer No.4) Silver / Gold / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528788980094', 'Female All Set Bestsellers (Offer No.4) Silver / Gold / Gold', 'Female All Set Bestsellers (Offer No.4) Silver / Gold / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528788947326', 'Female All Set Bestsellers (Offer No.4) Gold / Silver / Silver', 'Female All Set Bestsellers (Offer No.4) Gold / Silver / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528788914558', 'Female All Set Bestsellers (Offer No.4) Gold / Silver / Gold', 'Female All Set Bestsellers (Offer No.4) Gold / Silver / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528788881790', 'Female All Set Bestsellers (Offer No.4) Gold / Gold / Silver', 'Female All Set Bestsellers (Offer No.4) Gold / Gold / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528788849022', 'Female All Set Bestsellers (Offer No.4) Gold / Gold / Gold', 'Female All Set Bestsellers (Offer No.4) Gold / Gold / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528778527102', 'Female Stackable Bestsellers (Offer No.3) Silver / Silver', 'Female Stackable Bestsellers (Offer No.3) Silver / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528778494334', 'Female Stackable Bestsellers (Offer No.3) Silver / Gold', 'Female Stackable Bestsellers (Offer No.3) Silver / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528778461566', 'Female Stackable Bestsellers (Offer No.3) Gold / Silver', 'Female Stackable Bestsellers (Offer No.3) Gold / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528778428798', 'Female Stackable Bestsellers (Offer No.3) Gold / Gold', 'Female Stackable Bestsellers (Offer No.3) Gold / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528774660478', 'Women''s Bestsellers Bundle Silver / Silver / Gold', 'Women''s Bestsellers Bundle Silver / Silver / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528774594942', 'Women''s Bestsellers Bundle Silver / Gold / Gold', 'Women''s Bestsellers Bundle Silver / Gold / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528774529406', 'Women''s Bestsellers Bundle Gold / Silver / Gold', 'Women''s Bestsellers Bundle Gold / Silver / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528774463870', 'Women''s Bestsellers Bundle Gold / Gold / Gold', 'Women''s Bestsellers Bundle Gold / Gold / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528767418750', 'Full Female Set - (Offer No.1) Silver / Silver / Silver', 'Full Female Set - (Offer No.1) Silver / Silver / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528767385982', 'Full Female Set - (Offer No.1) Silver / Silver / Gold', 'Full Female Set - (Offer No.1) Silver / Silver / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528767353214', 'Full Female Set - (Offer No.1) Silver / Gold / Silver', 'Full Female Set - (Offer No.1) Silver / Gold / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528767320446', 'Full Female Set - (Offer No.1) Silver / Gold / Gold', 'Full Female Set - (Offer No.1) Silver / Gold / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528767287678', 'Full Female Set - (Offer No.1) Gold / Silver / Silver', 'Full Female Set - (Offer No.1) Gold / Silver / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528767254910', 'Full Female Set - (Offer No.1) Gold / Silver / Gold', 'Full Female Set - (Offer No.1) Gold / Silver / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528767222142', 'Full Female Set - (Offer No.1) Gold / Gold / Silver', 'Full Female Set - (Offer No.1) Gold / Gold / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528767189374', 'Full Female Set - (Offer No.1) Gold / Gold / Gold', 'Full Female Set - (Offer No.1) Gold / Gold / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528756998526', '925 Silver Bestsellers (Offer No.5)', '925 Silver Bestsellers (Offer No.5)', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528753000830', '925 Silver Bestsellers (Offer No.4)', '925 Silver Bestsellers (Offer No.4)', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528749199742', '925 Silver Bestsellers (Offer No.3)', '925 Silver Bestsellers (Offer No.3)', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528710926718', 'Full Male Set (Offer No.2) Gold / Gold / Gold', 'Full Male Set (Offer No.2) Gold / Gold / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528710893950', 'Full Male Set (Offer No.2) Gold / Gold / Silver', 'Full Male Set (Offer No.2) Gold / Gold / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528710861182', 'Full Male Set (Offer No.2) Gold / Silver / Gold', 'Full Male Set (Offer No.2) Gold / Silver / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528710828414', 'Full Male Set (Offer No.2) Gold / Silver / Silver', 'Full Male Set (Offer No.2) Gold / Silver / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528710795646', 'Full Male Set (Offer No.2) Silver / Gold / Gold', 'Full Male Set (Offer No.2) Silver / Gold / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528710762878', 'Full Male Set (Offer No.2) Silver / Gold / Silver', 'Full Male Set (Offer No.2) Silver / Gold / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528710730110', 'Full Male Set (Offer No.2) Silver / Silver / Gold', 'Full Male Set (Offer No.2) Silver / Silver / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528710697342', 'Full Male Set (Offer No.2) Silver / Silver / Silver', 'Full Male Set (Offer No.2) Silver / Silver / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528705192318', 'Male Bracelet Bestsellers (Offer No.1) Gold / Gold / Gold', 'Male Bracelet Bestsellers (Offer No.1) Gold / Gold / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528705159550', 'Men''s Bestsellers Bundle Gold / Gold', 'Men''s Bestsellers Bundle Gold / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528705126782', 'Male Bracelet Bestsellers (Offer No.1) Gold / Silver / Gold', 'Male Bracelet Bestsellers (Offer No.1) Gold / Silver / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528705094014', 'Men''s Bestsellers Bundle Gold / Silver', 'Men''s Bestsellers Bundle Gold / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528705061246', 'Male Bracelet Bestsellers (Offer No.1) Silver / Gold / Gold', 'Male Bracelet Bestsellers (Offer No.1) Silver / Gold / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528705028478', 'Men''s Bestsellers Bundle Silver / Gold', 'Men''s Bestsellers Bundle Silver / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528704995710', 'Male Bracelet Bestsellers (Offer No.1) Silver / Silver / Gold', 'Male Bracelet Bestsellers (Offer No.1) Silver / Silver / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('56528704962942', 'Men''s Bestsellers Bundle Silver / Silver', 'Men''s Bestsellers Bundle Silver / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('50805063418196', 'Test product', 'Test product', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('50489794363732', 'Test bundle Gold / Gold / Gold', 'Test bundle Gold / Gold / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('50489794232660', 'Test bundle Gold / Gold / Silver', 'Test bundle Gold / Gold / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('50489794134356', 'Test bundle Gold / Silver / Gold', 'Test bundle Gold / Silver / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('50489794101588', 'Test bundle Silver / Gold / Gold', 'Test bundle Silver / Gold / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('50489794068820', 'Test bundle Silver / Gold / Silver', 'Test bundle Silver / Gold / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('50489794036052', 'Test bundle Silver / Silver / Gold', 'Test bundle Silver / Silver / Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('50489794003284', 'Test bundle Silver / Silver / Silver', 'Test bundle Silver / Silver / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('50482765201748', 'Test bundle Extra Small (Fits XXS-XS) / Extra Small (Fits XXS-XS) / Extra Small (Fits XXS-XS)', 'Test bundle Extra Small (Fits XXS-XS) / Extra Small (Fits XXS-XS) / Extra Small (Fits XXS-XS)', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('50482765103444', 'Test bundle Extra Small (Fits XXS-XS) / Extra Small (Fits XXS-XS) / Extra Large (Fits XL- XXL)', 'Test bundle Extra Small (Fits XXS-XS) / Extra Small (Fits XXS-XS) / Extra Large (Fits XL- XXL)', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('50482764972372', 'Test bundle Extra Small (Fits XXS-XS) / Extra Small (Fits XXS-XS) / Regular - Fits Most (Small to Large)', 'Test bundle Extra Small (Fits XXS-XS) / Extra Small (Fits XXS-XS) / Regular - Fits Most (Small to Large)', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('50482764906836', 'Test bundle Extra Small (Fits XXS-XS) / Extra Large (Fits XL- XXL) / Extra Small (Fits XXS-XS)', 'Test bundle Extra Small (Fits XXS-XS) / Extra Large (Fits XL- XXL) / Extra Small (Fits XXS-XS)', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('50482764841300', 'Test bundle Extra Small (Fits XXS-XS) / Extra Large (Fits XL- XXL) / Extra Large (Fits XL- XXL)', 'Test bundle Extra Small (Fits XXS-XS) / Extra Large (Fits XL- XXL) / Extra Large (Fits XL- XXL)', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('50482764775764', 'Test bundle Extra Small (Fits XXS-XS) / Extra Large (Fits XL- XXL) / Regular - Fits Most (Small to Large)', 'Test bundle Extra Small (Fits XXS-XS) / Extra Large (Fits XL- XXL) / Regular - Fits Most (Small to Large)', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('50482764742996', 'Test bundle Extra Small (Fits XXS-XS) / Regular - Fits Most (Small to Large) / Extra Small (Fits XXS-XS)', 'Test bundle Extra Small (Fits XXS-XS) / Regular - Fits Most (Small to Large) / Extra Small (Fits XXS-XS)', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('50482764710228', 'Test bundle Extra Small (Fits XXS-XS) / Regular - Fits Most (Small to Large) / Extra Large (Fits XL- XXL)', 'Test bundle Extra Small (Fits XXS-XS) / Regular - Fits Most (Small to Large) / Extra Large (Fits XL- XXL)', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('50482764644692', 'Test bundle Extra Small (Fits XXS-XS) / Regular - Fits Most (Small to Large) / Regular - Fits Most (Small to Large)', 'Test bundle Extra Small (Fits XXS-XS) / Regular - Fits Most (Small to Large) / Regular - Fits Most (Small to Large)', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('50482764546388', 'Test bundle Extra Large (Fits XL- XXL) / Extra Small (Fits XXS-XS) / Extra Small (Fits XXS-XS)', 'Test bundle Extra Large (Fits XL- XXL) / Extra Small (Fits XXS-XS) / Extra Small (Fits XXS-XS)', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('50482764415316', 'Test bundle Extra Large (Fits XL- XXL) / Extra Small (Fits XXS-XS) / Extra Large (Fits XL- XXL)', 'Test bundle Extra Large (Fits XL- XXL) / Extra Small (Fits XXS-XS) / Extra Large (Fits XL- XXL)', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('50482764382548', 'Test bundle Extra Large (Fits XL- XXL) / Extra Small (Fits XXS-XS) / Regular - Fits Most (Small to Large)', 'Test bundle Extra Large (Fits XL- XXL) / Extra Small (Fits XXS-XS) / Regular - Fits Most (Small to Large)', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('50482764284244', 'Test bundle Extra Large (Fits XL- XXL) / Extra Large (Fits XL- XXL) / Extra Small (Fits XXS-XS)', 'Test bundle Extra Large (Fits XL- XXL) / Extra Large (Fits XL- XXL) / Extra Small (Fits XXS-XS)', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('50482764185940', 'Test bundle Extra Large (Fits XL- XXL) / Extra Large (Fits XL- XXL) / Extra Large (Fits XL- XXL)', 'Test bundle Extra Large (Fits XL- XXL) / Extra Large (Fits XL- XXL) / Extra Large (Fits XL- XXL)', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('50482764120404', 'Test bundle Extra Large (Fits XL- XXL) / Extra Large (Fits XL- XXL) / Regular - Fits Most (Small to Large)', 'Test bundle Extra Large (Fits XL- XXL) / Extra Large (Fits XL- XXL) / Regular - Fits Most (Small to Large)', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('50482764022100', 'Test bundle Extra Large (Fits XL- XXL) / Regular - Fits Most (Small to Large) / Extra Small (Fits XXS-XS)', 'Test bundle Extra Large (Fits XL- XXL) / Regular - Fits Most (Small to Large) / Extra Small (Fits XXS-XS)', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('50482763956564', 'Test bundle Extra Large (Fits XL- XXL) / Regular - Fits Most (Small to Large) / Extra Large (Fits XL- XXL)', 'Test bundle Extra Large (Fits XL- XXL) / Regular - Fits Most (Small to Large) / Extra Large (Fits XL- XXL)', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('50482763891028', 'Test bundle Extra Large (Fits XL- XXL) / Regular - Fits Most (Small to Large) / Regular - Fits Most (Small to Large)', 'Test bundle Extra Large (Fits XL- XXL) / Regular - Fits Most (Small to Large) / Regular - Fits Most (Small to Large)', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('50482763825492', 'Test bundle Regular - Fits Most (Small to Large) / Extra Small (Fits XXS-XS) / Extra Small (Fits XXS-XS)', 'Test bundle Regular - Fits Most (Small to Large) / Extra Small (Fits XXS-XS) / Extra Small (Fits XXS-XS)', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('50482763792724', 'Test bundle Regular - Fits Most (Small to Large) / Extra Small (Fits XXS-XS) / Extra Large (Fits XL- XXL)', 'Test bundle Regular - Fits Most (Small to Large) / Extra Small (Fits XXS-XS) / Extra Large (Fits XL- XXL)', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('50482763694420', 'Test bundle Regular - Fits Most (Small to Large) / Extra Small (Fits XXS-XS) / Regular - Fits Most (Small to Large)', 'Test bundle Regular - Fits Most (Small to Large) / Extra Small (Fits XXS-XS) / Regular - Fits Most (Small to Large)', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('50482763661652', 'Test bundle Regular - Fits Most (Small to Large) / Extra Large (Fits XL- XXL) / Extra Small (Fits XXS-XS)', 'Test bundle Regular - Fits Most (Small to Large) / Extra Large (Fits XL- XXL) / Extra Small (Fits XXS-XS)', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('50482763596116', 'Test bundle Regular - Fits Most (Small to Large) / Extra Large (Fits XL- XXL) / Extra Large (Fits XL- XXL)', 'Test bundle Regular - Fits Most (Small to Large) / Extra Large (Fits XL- XXL) / Extra Large (Fits XL- XXL)', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('50482763530580', 'Test bundle Regular - Fits Most (Small to Large) / Extra Large (Fits XL- XXL) / Regular - Fits Most (Small to Large)', 'Test bundle Regular - Fits Most (Small to Large) / Extra Large (Fits XL- XXL) / Regular - Fits Most (Small to Large)', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('50482763497812', 'Test bundle Regular - Fits Most (Small to Large) / Regular - Fits Most (Small to Large) / Extra Small (Fits XXS-XS)', 'Test bundle Regular - Fits Most (Small to Large) / Regular - Fits Most (Small to Large) / Extra Small (Fits XXS-XS)', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('50482763432276', 'Test bundle Regular - Fits Most (Small to Large) / Regular - Fits Most (Small to Large) / Extra Large (Fits XL- XXL)', 'Test bundle Regular - Fits Most (Small to Large) / Regular - Fits Most (Small to Large) / Extra Large (Fits XL- XXL)', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('50482763399508', 'Test bundle Gold / Silver / Silver', 'Test bundle Gold / Silver / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('49651158286676', 'Bracelet Essential Stack Gold / Silver / Silver', 'Bracelet Essential Stack Gold / Silver / Silver', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('49230306705748', '‍Vacier Gift Box and Cloth (100% off)', 'Paperboard packaging box', 3.00, '48195000', 'EUR', true, 'classified-products.csv'),
	('49226377199956', '‍Vacier Gift Box (100% off)', '‍Vacier Gift Box (100% off)', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('47219183092052', 'Copy of BOX CHAIN NECKLACE Gold', 'Copy of BOX CHAIN NECKLACE Gold', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('46680345641300', 'VERSATILE VACIER WALLET (100% off)', 'Wallet with outer surface of plastic sheeting', 0.00, '42023210', 'EUR', true, 'classified-products.csv'),
	('46679085482324', 'Silver Cloth (100% off)', 'Microfiber cleaning cloth', 2.00, '63071090', 'EUR', true, 'classified-products.csv'),
	('43059294339258', 'VERSATILE VACIER WALLET (100% off)', 'VERSATILE VACIER WALLET (100% off)', 0.00, '0', 'EUR', true, 'classified-products.csv'),
	('4.92303E+13', '‍Vacier Gift Box and Cloth (100% off)', '‍Vacier Gift Box and Cloth (100% off)', 3.00, '71131120', 'EUR', true, 'classified-products.csv'),
	('4.72192E+13', 'Copy of BOX CHAIN NECKLACE Gold', 'Copy of BOX CHAIN NECKLACE Gold', 1.00, '711719', 'EUR', true, 'classified-products.csv'),
	('4.66803E+13', 'VERSATILE VACIER WALLET (100% off)', 'VERSATILE VACIER WALLET (100% off)', 0.00, '392310', 'EUR', true, 'classified-products.csv'),
	('4.66791E+13', 'Silver Cloth (100% off)', 'Silver Cloth (100% off)', 1.00, '630710', 'EUR', true, 'classified-products.csv')
ON CONFLICT DO NOTHING;
