ALTER TABLE "vacier_latam_customs_overrides"
  ALTER COLUMN "currency" SET DEFAULT 'USD';
--> statement-breakpoint
CREATE TEMP TABLE "_vacier_latam_customs_seed" (
  "sku" varchar(120) NOT NULL,
  "product_name" varchar(255),
  "customs_value" numeric(12, 2) NOT NULL,
  "currency" varchar(3) NOT NULL,
  "country_code" varchar(10) NOT NULL,
  "source" varchar(120),
  "notes" text
);
--> statement-breakpoint
INSERT INTO "_vacier_latam_customs_seed" (
  "sku", "product_name", "customs_value", "currency", "country_code", "source", "notes"
)
VALUES
  ('VROPSP01', 'EXCLUSIVE UNISIZE RING IN SILVER', 17.10, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Silver'),
  ('VBCUSP01', 'EXCLUSIVE UNISIZE CUFF IN SILVER', 31.80, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Silver'),
  ('VRSISP01', 'UNISIZE SIGNET RING IN SILVER', 18.40, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Silver'),
  ('VBSISP01', 'UNISIZE SIGNET CUFF IN SILVER', 40.10, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Silver'),
  ('VBOCSN01', 'OCTAGON BRACELET IN SILVER REGULAR (S-L)', 12.30, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Silver'),
  ('VBOCSN02', 'OCTAGON BRACELET IN SILVER LARGE (XL-XXL)', 13.30, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Silver'),
  ('VBOCSN03', 'OCTAGON BRACELET IN SILVER SMALL (XXS-XS)', 13.00, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Silver'),
  ('VNOCSN01', 'OCTAGON NECKLACE IN SILVER REGULAR', 18.50, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Silver'),
  ('VBCLSN01', 'CLIP CHAIN BRACELET IN SILVER (18cm)', 5.70, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Silver'),
  ('VBCLSN02', 'CLIP CHAIN BRACELET IN SILVER (20cm)', 6.20, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Silver'),
  ('VBCLSN03', 'CLIP CHAIN BRACELET IN SILVER (16cm)', 5.40, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Silver'),
  ('VNCLSN01', 'CLIP CHAIN NECKLACE (54cm)', 12.50, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Silver'),
  ('VRSISP02', 'Ripple Signet Ring in Silver', 16.40, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Silver'),
  ('VBSISP02', 'Ripple Signet Cuff in Silver', 33.80, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Silver'),
  ('VNSQMN02', 'Square Chain Necklace Silver', 2.50, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VNSQGN02', 'Square Chain Necklace Gold', 2.50, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VNSQMN01', 'Square Pendant Necklace Silver', 2.50, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VNSQGN01', 'Square Pendant Necklace Gold', 2.50, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VNBOMN02', 'Box Chain Necklace Silver', 2.50, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VNBOGN02', 'Box Chain Necklace Gold', 2.50, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VNBOMN01', 'Box Pendant Necklace Silver', 2.50, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VNBOGN01', 'Box Pendant Necklace Gold', 2.50, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VNWCMN02', 'Wire Chain Necklace Silver', 2.50, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VNWCGN02', 'Wire Chain Necklace Gold', 2.50, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VNWCMN01', 'Wire Pendant Necklace Silver', 2.50, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VNWCGN01', 'Wire Pendant Necklace Gold', 2.50, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VNCCMN02', 'Minimal Necklace Silver', 2.50, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VNCCGN02', 'Minimal Necklace Gold', 2.50, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VNCCMN01', 'Minimal Pendant Necklace Silver', 2.50, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VNCCGN01', 'Minimal Pendant Necklace Gold', 2.50, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBSQMN01', 'Square Chain Bracelet 18 CM Silver', 1.75, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBSQMN03', 'Square Chain Bracelet 15 CM Silver', 1.55, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBSQMN02', 'Square Chain Bracelet 20 CM Silver', 2.00, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBSQGN01', 'Square Chain Bracelet 18 CM Gold', 1.75, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBSQGN03', 'Square Chain Bracelet 15 CM Gold', 1.55, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBSQGN02', 'Square Chain Bracelet 20 CM Gold', 2.00, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBBOMN01', 'Box Chain Bracelet 18 CM Silver', 1.75, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBBOMN03', 'Box Chain Bracelet 15 CM Silver', 1.55, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBBOMN02', 'Box Chain Bracelet 20 CM Silver', 2.00, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBBOGN01', 'Box Chain Bracelet 18 CM Gold', 1.75, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBBOGN03', 'Box Chain Bracelet 15 CM Gold', 1.55, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBBOGN02', 'Box Chain Bracelet 20 CM Gold', 2.00, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBWCMN01', 'Wire Chain Bracelet 18 CM Silver', 1.75, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBWCMN03', 'Wire Chain Bracelet 15 CM Silver', 1.55, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBWCMN02', 'Wire Chain Bracelet 20 CM Silver', 2.00, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBWCGN01', 'Wire Chain Bracelet 18 CM Gold', 1.75, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBWCGN03', 'Wire Chain Bracelet 15 CM Gold', 1.55, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBWCGN02', 'Wire Chain Bracelet 20 CM Gold', 2.00, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBCCMN01', 'Minimal Bracelet 18 CM Silver', 1.75, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBCCMN03', 'Minimal Bracelet 15 CM Silver', 1.55, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBCCMN02', 'Minimal Bracelet 20 CM Silver', 2.00, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBCCGN01', 'Minimal Bracelet 18 CM Gold', 1.75, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBCCGN03', 'Minimal Bracelet 15 CM Gold', 1.55, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBCCGN02', 'Minimal Bracelet 20 CM Gold', 2.00, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VROPMB02', 'Unisize Ring Silver', 1.00, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VROPGB02', 'Unisize Ring Gold', 1.00, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBCUMB02', 'Unisize Cuff Silver', 3.00, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBCUGB02', 'Unisize Cuff Gold', 3.00, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VROPMP02', 'Minimal Unisize Ring Silver', 1.00, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VROPGP02', 'Minimal Unisize Ring Gold', 1.00, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBCUMP02', 'Minimal Unisize Cuff Silver', 3.00, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBCUGP02', 'Minimal Unisize Cuff Gold', 3.00, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VNSEMP01', 'LINEAR CHAIN NECKLACE Silver', 2.50, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VNSEGP01', 'LINEAR CHAIN NECKLACE Gold', 2.50, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBSEMP03', 'LINEAR CHAIN BRACELET Extra Small (Fits XXS-XS) / Silver', 1.55, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBSEMP02', 'LINEAR CHAIN BRACELET Extra Large (Fits XL- XXL) / Silver', 2.00, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBSEMP01', 'LINEAR CHAIN BRACELET Regular - Fits Most (Small to Large) / Silver', 1.75, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBSEGP03', 'LINEAR CHAIN BRACELET Extra Small (Fits XXS-XS) / Gold', 1.55, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBSEGP02', 'LINEAR CHAIN BRACELET Extra Large (Fits XL- XXL) / Gold', 2.00, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBSEGP01', 'LINEAR CHAIN BRACELET Regular - Fits Most (Small to Large) / Gold', 1.75, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VROPSSP01', 'UNISIZE RING | STACKABLE | POLISHED | SILVER', 0.95, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VROPSGP02', 'UNISIZE RING | STACKABLE | POLISHED | GOLD', 0.95, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBCUSSP01', 'UNISIZE CUFF | STACKABLE | POLISHED | SILVER', 2.20, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBCUSGP02', 'UNISIZE CUFF | STACKABLE | POLISHED | GOLD', 2.20, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VROPBMB03', 'UNISIZE RING | STACKABLE | BLACK', 0.95, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VROPBMB02', 'UNISIZE RING Black', 0.95, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VROPBMB01', 'MINIMAL UNISIZE RING Black', 0.95, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VNWCBMB02', 'WIRE PENDANT NECKLACE Black', 2.50, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VNWCBMB01', 'WIRE CHAIN NECKLACE Black', 2.50, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VNSQBMB02', 'SQUARE PENDANT NECKLACE Black', 2.50, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VNSQBMB01', 'SQUARE CHAIN NECKLACE Black', 2.50, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VNSEBMB01', 'SEED CHAIN NECKLACE / Black', 2.50, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VNCCBMB02', 'MINIMAL PENDANT NECKLACE Black', 2.50, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VNCCBMB01', 'MINIMAL CHAIN NECKLACE (Copy) Black', 2.50, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VNBOBMB02', 'BOX PENDANT NECKLACE Black', 2.50, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VNBOBMB01', 'BOX CHAIN NECKLACE Black', 2.50, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBWCBMB03', 'WIRE CHAIN BRACELET Extra Small (Fits XXS-XS) / Black', 1.55, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBWCBMB02', 'WIRE CHAIN BRACELET Extra Large (Fits XL- XXL) / Black', 2.00, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBWCBMB01', 'WIRE CHAIN BRACELET Regular - Fits Most (Small to Large) / Black', 1.75, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBSQBMB03', 'SQUARE CHAIN BRACELET Extra Small (Fits XXS-XS) / Black', 1.55, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBSQBMB02', 'SQUARE CHAIN BRACELET Extra Large (Fits XL- XXL) / Black', 2.00, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBSQBMB01', 'SQUARE CHAIN BRACELET Regular - Fits Most (Small to Large) / Black', 1.75, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBSEBMB03', 'Extra Small (Fits XXS-XS) / Black SEED CHAIN BRACELET', 1.55, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBSEBMB02', 'Extra Large (Fits XL- XXL) / Black LINEAR CHAIN BRACELET', 2.00, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBSEBMB01', 'Regular - Fits Most (Small to Large) / Black LINEAR CHAIN BRACELET', 1.75, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBCUBMB03', 'UNISIZE CUFF | STACKABLE | BLACK', 2.20, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBCUBMB02', 'UNISIZE CUFF Black', 3.00, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBCUBMB01', 'MINIMAL UNISIZE CUFF Black', 3.00, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBCCBMB03', 'MINIMAL CHAIN BRACELET Extra Small (Fits XXS-XS) / Black', 1.55, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBCCBMB02', 'MINIMAL CHAIN BRACELET Extra Large (Fits XL- XXL) / Black', 2.00, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBCCBMB01', 'MINIMAL CHAIN BRACELET Regular - Fits Most (Small to Large) / Black', 1.75, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBBOBMB03', 'BOX CHAIN BRACELET Extra Small (Fits XXS-XS) / Black', 1.55, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBBOBMB02', 'BOX CHAIN BRACELET Extra Large (Fits XL- XXL) / Black', 2.00, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('VBBOBMB01', 'BOX CHAIN BRACELET Regular - Fits Most (Small to Large) / Black', 1.75, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Stainless Steel'),
  ('WRMNGP01', 'LINEAR RING IN GOLD', 1.95, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Female'),
  ('WRMNMP01', 'LINEAR RING IN SILVER', 1.95, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Female'),
  ('WBMNGP01', 'LINEAR CUFF IN GOLD', 2.25, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Female'),
  ('WBMNMP01', 'LINEAR CUFF IN SILVER', 2.25, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Female'),
  ('WEMNGP01', 'LINEAR HOOP EARRINGS IN GOLD', 3.00, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Female'),
  ('WEMNMP01', 'LINEAR HOOP EARRINGS IN SILVER', 3.00, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Female'),
  ('WRCYGP01', 'FLUID RING IN GOLD', 1.95, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Female'),
  ('WRCYMP01', 'FLUID RING IN SILVER', 1.95, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Female'),
  ('WBCYGP01', 'FLUID CUFF IN GOLD', 2.25, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Female'),
  ('WBCYMP01', 'FLUID CUFF IN SILVER', 2.25, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Female'),
  ('WECYGP01', 'FLUID HOOP EARRINGS IN GOLD', 3.00, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Female'),
  ('WECYMP01', 'FLUID HOOP EARRINGS IN SILVER', 3.00, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Female'),
  ('WNBXGP01', 'BOX CHAIN NECKLACE IN GOLD', 2.75, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Female'),
  ('WNBXMP01', 'BOX CHAIN NECKLACE IN SILVER', 2.75, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Female'),
  ('WNDSGP01', 'BRAID CHAIN NECKLACE IN GOLD', 2.75, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Female'),
  ('WNDSMP01', 'BRAID CHAIN NECKLACE IN SILVER', 2.75, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Female'),
  ('WNSQGP01', 'SQUARE CHAIN NECKLACE IN GOLD', 2.75, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Female'),
  ('WNSQMP01', 'SQUARE CHAIN NECKLACE IN SILVER', 2.75, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Female'),
  ('WNFSGP01', 'FLUID CHAIN NECKLACE IN GOLD', 2.75, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Female'),
  ('WNFSMP01', 'FLUID CHAIN NECKLACE IN SILVER', 2.75, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Female'),
  ('WBFSGP01', 'FLUID CHAIN BRACELET IN GOLD', 2.05, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Female'),
  ('WBFSMP01', 'FLUID CHAIN BRACELET IN SILVER', 2.05, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Female'),
  ('WBDSGP01', 'BRAID CHAIN BRACELET IN GOLD', 2.05, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Female'),
  ('WBDSMP01', 'BRAID CHAIN BRACELET IN SILVER', 2.05, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Female'),
  ('WBSQGP01', 'SQUARE CHAIN BRACELET IN GOLD', 2.05, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Female'),
  ('WBSQMP01', 'SQUARE CHAIN BRACELET IN SILVER', 2.05, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Female'),
  ('WBBXGP01', 'BOX CHAIN BRACELET IN GOLD', 2.05, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Female'),
  ('WBBXMP01', 'BOX CHAIN BRACELET IN SILVER', 2.05, 'USD', 'ALL', 'LATAM Lowered Invoice Values.xlsx', 'Vacier LATAM workbook sheet: Female');
--> statement-breakpoint
DELETE FROM "vacier_latam_customs_overrides" AS target
USING "_vacier_latam_customs_seed" AS seed
WHERE target."sku" = seed."sku";
--> statement-breakpoint
INSERT INTO "vacier_latam_customs_overrides" (
  "sku",
  "product_name",
  "customs_value",
  "currency",
  "country_code",
  "is_active",
  "source",
  "notes",
  "updated_by"
)
SELECT
  "sku",
  "product_name",
  "customs_value",
  "currency",
  "country_code",
  true,
  "source",
  "notes",
  'migration_0013'
FROM "_vacier_latam_customs_seed";
--> statement-breakpoint
DROP TABLE "_vacier_latam_customs_seed";
